server:
  port: 7001
eureka:
  instance:
    hostname: 129.204.122.20
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://121.36.48.89:7001/eureka/



