server:
  port: 7002
eureka:
  instance:
    hostname: 121.36.48.89
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://129.204.122.20:7001/eureka/
